// External Spanish vocabulary data imported from vocabulary.js
// This file is loaded before spanish-game.js and provides supplemental
// row arrays without overriding the built-in game data.
window.EXTERNAL_SPANISH_VOCABULARY = {
  verbs: [
  ["ser", "to be"],
  ["estar", "to be"],
  ["tener", "to have"],
  ["haber", "to have / there is / there are"],
  ["hacer", "to do / to make"],
  ["ir", "to go"],
  ["venir", "to come"],
  ["decir", "to say / to tell"],
  ["poder", "to be able to / can"],
  ["querer", "to want / to love"],
  ["deber", "must / should / to owe"],
  ["saber", "to know (information)"],
  ["conocer", "to know / to be familiar with"],
  ["ver", "to see"],
  ["dar", "to give"],
  ["poner", "to put"],
  ["salir", "to leave / to go out"],
  ["llegar", "to arrive"],
  ["llevar", "to carry / to wear / to take"],
  ["dejar", "to leave / to let"],
  ["seguir", "to follow / to continue"],
  ["encontrar", "to find"],
  ["buscar", "to look for"],
  ["pensar", "to think"],
  ["creer", "to believe"],
  ["sentir", "to feel"],
  ["parecer", "to seem"],
  ["quedar", "to stay / to remain / to fit"],
  ["pasar", "to pass / to happen / to spend time"],
  ["volver", "to return / to do again"],
  ["tomar", "to take / to drink"],
  ["usar", "to use"],
  ["necesitar", "to need"],
  ["gustar", "to like / to be pleasing"],
  ["preferir", "to prefer"],
  ["esperar", "to wait / to hope"],
  ["intentar", "to try"],
  ["tratar", "to try / to treat"],
  ["empezar", "to begin / to start"],
  ["comenzar", "to begin / to start"],
  ["terminar", "to finish"],
  ["acabar", "to finish / to have just"],
  ["continuar", "to continue"],
  ["cambiar", "to change"],
  ["ayudar", "to help"],
  ["trabajar", "to work"],
  ["estudiar", "to study"],
  ["aprender", "to learn"],
  ["enseñar", "to teach"],
  ["entender", "to understand"],
  ["explicar", "to explain"],
  ["recordar", "to remember"],
  ["olvidar", "to forget"],
  ["preguntar", "to ask"],
  ["responder", "to answer"],
  ["hablar", "to speak / to talk"],
  ["escuchar", "to listen"],
  ["leer", "to read"],
  ["escribir", "to write"],
  ["contar", "to count / to tell"],
  ["mostrar", "to show"],
  ["mirar", "to look at / to watch"],
  ["oír", "to hear"],
  ["conseguir", "to get / to obtain"],
  ["perder", "to lose / to miss"],
  ["ganar", "to win / to earn"],
  ["crear", "to create"],
  ["construir", "to build"],
  ["romper", "to break"],
  ["arreglar", "to fix"],
  ["cortar", "to cut"],
  ["abrir", "to open"],
  ["cerrar", "to close"],
  ["entrar", "to enter"],
  ["subir", "to go up / to upload"],
  ["bajar", "to go down / to download"],
  ["correr", "to run"],
  ["caminar", "to walk"],
  ["andar", "to walk / to go"],
  ["vivir", "to live"],
  ["morir", "to die"],
  ["nacer", "to be born"],
  ["dormir", "to sleep"],
  ["despertar", "to wake up"],
  ["comer", "to eat"],
  ["beber", "to drink"],
  ["cocinar", "to cook"],
  ["comprar", "to buy"],
  ["vender", "to sell"],
  ["pagar", "to pay"],
  ["costar", "to cost"],
  ["viajar", "to travel"],
  ["conducir", "to drive"],
  ["volar", "to fly"],
  ["nadar", "to swim"],
  ["jugar", "to play"],
  ["bailar", "to dance"],
  ["cantar", "to sing"],
  ["reír", "to laugh"],
  ["llorar", "to cry"],
  ["amar", "to love"],
  ["odiar", "to hate"],
  ["decidir", "to decide"],
  ["elegir", "to choose"],
  ["permitir", "to allow"],
  ["prohibir", "to prohibit"],
  ["mandar", "to order / to send"],
  ["recibir", "to receive"],
  ["enviar", "to send"],
  ["traer", "to bring"],
  ["regresar", "to return"],
  ["quedarse", "to stay"],
  ["levantarse", "to get up"],
  ["sentarse", "to sit down"],
  ["acostarse", "to go to bed"],
  ["vestirse", "to get dressed"],
  ["lavarse", "to wash oneself"],
  ["ducharse", "to shower"],
  ["afeitarse", "to shave"],
  ["preocuparse", "to worry"],
  ["divertirse", "to have fun"],
  ["sentirse", "to feel"],
  ["llamarse", "to be called"],
],
  commonVerbConstructions: [
  ["tener que", "to have to"],
  ["tener ganas de", "to feel like"],
  ["tener miedo de", "to be afraid of"],
  ["tener razón", "to be right"],
  ["tener cuidado", "to be careful"],
  ["tener suerte", "to be lucky"],
  ["tener tiempo", "to have time"],
  ["tener lugar", "to take place"],
  ["tener éxito", "to be successful"],
  ["ir a", "to be going to"],
  ["venir de", "to come from / to have just"],
  ["volver a", "to do again"],
  ["acabar de", "to have just done"],
  ["dejar de", "to stop doing"],
  ["empezar a", "to start doing"],
  ["comenzar a", "to begin doing"],
  ["seguir + gerund", "to continue doing"],
  ["estar + gerund", "to be doing"],
  ["estar a punto de", "to be about to"],
  ["ponerse a", "to start doing"],
  ["llegar a", "to manage to / to come to"],
  ["deber de", "should / must probably"],
  ["poder + infinitive", "to be able to"],
  ["querer + infinitive", "to want to"],
  ["necesitar + infinitive", "to need to"],
  ["preferir + infinitive", "to prefer to"],
  ["intentar + infinitive", "to try to"],
  ["tratar de", "to try to"],
  ["aprender a", "to learn to"],
  ["ayudar a", "to help"],
  ["enseñar a", "to teach"],
  ["decidir + infinitive", "to decide to"],
  ["esperar + infinitive", "to hope to / expect to"],
  ["pensar + infinitive", "to plan to / intend to"],
  ["pensar en", "to think about"],
  ["hablar de", "to talk about"],
  ["hablar con", "to talk with"],
  ["depender de", "to depend on"],
  ["confiar en", "to trust / rely on"],
  ["creer en", "to believe in"],
  ["acordarse de", "to remember"],
  ["olvidarse de", "to forget"],
  ["darse cuenta de", "to realize"],
  ["enamorarse de", "to fall in love with"],
  ["llevarse bien con", "to get along with"],
  ["llevarse mal con", "to get along badly with"],
  ["tener que ver con", "to have to do with"],
  ["preocuparse por", "to worry about"],
  ["interesarse por", "to be interested in"],
  ["participar en", "to participate in"],
  ["convertirse en", "to become"],
  ["cuidar de", "to take care of"],
  ["acostumbrarse a", "to get used to"],
],
  nouns: [
  ["persona", "person"],
  ["hombre", "man"],
  ["mujer", "woman"],
  ["niño", "boy / child"],
  ["niña", "girl / child"],
  ["bebé", "baby"],
  ["adulto", "adult"],
  ["adolescente", "teenager"],
  ["joven", "young person"],
  ["amigo", "friend"],
  ["amiga", "female friend"],
  ["vecino", "neighbor"],
  ["vecina", "female neighbor"],
  ["conocido", "acquaintance"],
  ["pareja", "partner"],
  ["esposo", "husband"],
  ["esposa", "wife"],
  ["novio", "boyfriend"],
  ["novia", "girlfriend"],
  ["padre", "father"],
  ["madre", "mother"],
  ["hijo", "son"],
  ["hija", "daughter"],
  ["hermano", "brother"],
  ["hermana", "sister"],
  ["abuelo", "grandfather"],
  ["abuela", "grandmother"],
  ["nieto", "grandson"],
  ["nieta", "granddaughter"],
  ["tío", "uncle"],
  ["tía", "aunt"],
  ["primo", "cousin"],
  ["prima", "cousin"],
  ["familia", "family"],
  ["jefe", "boss"],
  ["compañero", "coworker / companion"],
  ["profesor", "teacher / professor"],
  ["estudiante", "student"],
  ["cliente", "customer"],
  ["doctor", "doctor"],
  ["enfermero", "nurse"],
  ["policía", "police officer"],
  ["casa", "house"],
  ["hogar", "home"],
  ["apartamento", "apartment"],
  ["habitación", "room"],
  ["cuarto", "room"],
  ["cocina", "kitchen"],
  ["baño", "bathroom"],
  ["dormitorio", "bedroom"],
  ["sala", "living room"],
  ["comedor", "dining room"],
  ["garaje", "garage"],
  ["jardín", "garden"],
  ["puerta", "door"],
  ["ventana", "window"],
  ["pared", "wall"],
  ["piso", "floor"],
  ["techo", "ceiling / roof"],
  ["escalera", "staircase"],
  ["mesa", "table"],
  ["silla", "chair"],
  ["cama", "bed"],
  ["sofá", "sofa"],
  ["escritorio", "desk"],
  ["armario", "closet / wardrobe"],
  ["espejo", "mirror"],
  ["lámpara", "lamp"],
  ["luz", "light"],
  ["llave", "key"],
  ["reloj", "clock / watch"],
  ["teléfono", "phone"],
  ["cargador", "charger"],
  ["computadora", "computer"],
  ["comida", "food"],
  ["bebida", "drink"],
  ["agua", "water"],
  ["café", "coffee"],
  ["té", "tea"],
  ["leche", "milk"],
  ["jugo", "juice"],
  ["pan", "bread"],
  ["arroz", "rice"],
  ["pasta", "pasta"],
  ["carne", "meat"],
  ["pollo", "chicken"],
  ["pescado", "fish"],
  ["huevo", "egg"],
  ["queso", "cheese"],
  ["mantequilla", "butter"],
  ["sal", "salt"],
  ["azúcar", "sugar"],
  ["fruta", "fruit"],
  ["verdura", "vegetable"],
  ["manzana", "apple"],
  ["naranja", "orange"],
  ["plátano", "banana"],
  ["limón", "lemon"],
  ["fresa", "strawberry"],
  ["tomate", "tomato"],
  ["papa", "potato"],
  ["cebolla", "onion"],
  ["zanahoria", "carrot"],
  ["lechuga", "lettuce"],
  ["sopa", "soup"],
  ["ensalada", "salad"],
  ["sándwich", "sandwich"],
  ["desayuno", "breakfast"],
  ["almuerzo", "lunch"],
  ["cena", "dinner"],
  ["postre", "dessert"],
  ["restaurante", "restaurant"],
  ["menú", "menu"],
  ["cuenta", "bill / check"],
  ["ropa", "clothing"],
  ["camisa", "shirt"],
  ["camiseta", "T-shirt"],
  ["pantalón", "pants"],
  ["pantalones", "pants"],
  ["vaqueros", "jeans"],
  ["chaqueta", "jacket"],
  ["abrigo", "coat"],
  ["suéter", "sweater"],
  ["vestido", "dress"],
  ["falda", "skirt"],
  ["zapato", "shoe"],
  ["zapatilla", "sneaker"],
  ["bota", "boot"],
  ["calcetín", "sock"],
  ["sombrero", "hat"],
  ["gorra", "cap"],
  ["guante", "glove"],
  ["bufanda", "scarf"],
  ["cinturón", "belt"],
  ["bolso", "bag / purse"],
  ["mochila", "backpack"],
  ["coche", "car"],
  ["auto", "car"],
  ["camión", "truck"],
  ["autobús", "bus"],
  ["tren", "train"],
  ["avión", "airplane"],
  ["barco", "boat"],
  ["bicicleta", "bicycle"],
  ["motocicleta", "motorcycle"],
  ["taxi", "taxi"],
  ["metro", "subway"],
  ["estación", "station"],
  ["aeropuerto", "airport"],
  ["puerto", "port"],
  ["carretera", "road / highway"],
  ["calle", "street"],
  ["camino", "path / road"],
  ["puente", "bridge"],
  ["semáforo", "traffic light"],
  ["mapa", "map"],
  ["billete", "ticket"],
  ["pasaje", "ticket / passage"],
  ["viaje", "trip"],
  ["gasolina", "gasoline"],
  ["motor", "engine"],
  ["rueda", "wheel"],
  ["neumático", "tire"],
  ["volante", "steering wheel"],
  ["ciudad", "city"],
  ["pueblo", "town"],
  ["país", "country"],
  ["estado", "state"],
  ["capital", "capital"],
  ["centro", "center / downtown"],
  ["barrio", "neighborhood"],
  ["tienda", "store"],
  ["mercado", "market"],
  ["supermercado", "supermarket"],
  ["banco", "bank"],
  ["escuela", "school"],
  ["universidad", "university"],
  ["hospital", "hospital"],
  ["farmacia", "pharmacy"],
  ["oficina", "office"],
  ["hotel", "hotel"],
  ["bar", "bar"],
  ["parque", "park"],
  ["playa", "beach"],
  ["montaña", "mountain"],
  ["río", "river"],
  ["lago", "lake"],
  ["mar", "sea"],
  ["océano", "ocean"],
  ["bosque", "forest"],
  ["campo", "countryside / field"],
  ["granja", "farm"],
  ["iglesia", "church"],
  ["museo", "museum"],
  ["biblioteca", "library"],
  ["gimnasio", "gym"],
  ["trabajo", "work / job"],
  ["empleo", "employment / job"],
  ["empresa", "company"],
  ["reunión", "meeting"],
  ["proyecto", "project"],
  ["problema", "problem"],
  ["solución", "solution"],
  ["tarea", "task / homework"],
  ["clase", "class"],
  ["curso", "course"],
  ["examen", "exam"],
  ["pregunta", "question"],
  ["respuesta", "answer"],
  ["libro", "book"],
  ["cuaderno", "notebook"],
  ["papel", "paper"],
  ["lápiz", "pencil"],
  ["bolígrafo", "pen"],
  ["pantalla", "screen"],
  ["teclado", "keyboard"],
  ["ratón", "mouse"],
  ["tecnología", "technology"],
  ["ordenador", "computer"],
  ["móvil", "cellphone"],
  ["internet", "internet"],
  ["red", "network"],
  ["sitio", "site"],
  ["página", "page"],
  ["aplicación", "application / app"],
  ["programa", "program"],
  ["archivo", "file"],
  ["carpeta", "folder"],
  ["foto", "photo"],
  ["imagen", "image"],
  ["vídeo", "video"],
  ["mensaje", "message"],
  ["correo", "email / mail"],
  ["contraseña", "password"],
  ["batería", "battery"],
  ["cable", "cable"],
  ["botón", "button"],
  ["enlace", "link"],
  ["naturaleza", "nature"],
  ["sol", "sun"],
  ["luna", "moon"],
  ["estrella", "star"],
  ["cielo", "sky"],
  ["nube", "cloud"],
  ["lluvia", "rain"],
  ["nieve", "snow"],
  ["viento", "wind"],
  ["tormenta", "storm"],
  ["trueno", "thunder"],
  ["relámpago", "lightning"],
  ["calor", "heat"],
  ["frío", "cold"],
  ["temperatura", "temperature"],
  ["árbol", "tree"],
  ["flor", "flower"],
  ["planta", "plant"],
  ["hierba", "grass"],
  ["hoja", "leaf"],
  ["animal", "animal"],
  ["perro", "dog"],
  ["gato", "cat"],
  ["pájaro", "bird"],
  ["pez", "fish"],
  ["caballo", "horse"],
  ["vaca", "cow"],
  ["cuerpo", "body"],
  ["cabeza", "head"],
  ["cara", "face"],
  ["ojo", "eye"],
  ["oreja", "ear"],
  ["nariz", "nose"],
  ["boca", "mouth"],
  ["diente", "tooth"],
  ["cuello", "neck"],
  ["hombro", "shoulder"],
  ["brazo", "arm"],
  ["mano", "hand"],
  ["dedo", "finger"],
  ["pecho", "chest"],
  ["espalda", "back"],
  ["estómago", "stomach"],
  ["pierna", "leg"],
  ["rodilla", "knee"],
  ["pie", "foot"],
  ["corazón", "heart"],
  ["sangre", "blood"],
  ["piel", "skin"],
  ["pelo", "hair"],
  ["salud", "health"],
  ["enfermedad", "illness / disease"],
  ["dolor", "pain"],
  ["fiebre", "fever"],
  ["tos", "cough"],
  ["medicina", "medicine"],
  ["médico", "doctor"],
  ["enfermera", "nurse"],
  ["paciente", "patient"],
  ["emergencia", "emergency"],
  ["accidente", "accident"],
  ["herida", "wound"],
  ["cita", "appointment"],
  ["síntoma", "symptom"],
  ["amor", "love"],
  ["odio", "hate"],
  ["felicidad", "happiness"],
  ["tristeza", "sadness"],
  ["miedo", "fear"],
  ["esperanza", "hope"],
  ["suerte", "luck"],
  ["éxito", "success"],
  ["fracaso", "failure"],
  ["idea", "idea"],
  ["razón", "reason"],
  ["verdad", "truth"],
  ["mentira", "lie"],
  ["tiempo", "time"],
  ["vida", "life"],
  ["muerte", "death"],
  ["mundo", "world"],
  ["forma", "way / form"],
  ["manera", "way / manner"],
  ["cosa", "thing"],
  ["parte", "part"],
  ["lugar", "place"],
  ["vez", "time / occasion"],
  ["momento", "moment"],
  ["ejemplo", "example"],
  ["historia", "story / history"],
  ["decisión", "decision"],
  ["cambio", "change"],
  ["oportunidad", "opportunity"],
  ["resultado", "result"],
  ["objetivo", "goal"],
  ["plan", "plan"],
  ["dinero", "money"],
  ["precio", "price"],
  ["costo", "cost"],
  ["producto", "product"],
  ["artículo", "item"],
  ["compra", "purchase"],
  ["venta", "sale"],
  ["oferta", "offer / sale"],
  ["descuento", "discount"],
  ["vendedor", "salesperson"],
  ["tarjeta", "card"],
  ["efectivo", "cash"],
  ["moneda", "coin / currency"],
  ["recibo", "receipt"],
  ["deporte", "sport"],
  ["juego", "game"],
  ["equipo", "team"],
  ["jugador", "player"],
  ["entrenador", "coach"],
  ["partido", "match / game"],
  ["competencia", "competition"],
  ["pelota", "ball"],
  ["pista", "court / track"],
  ["carrera", "race / run"],
  ["ejercicio", "exercise"],
  ["fútbol", "soccer"],
  ["baloncesto", "basketball"],
  ["tenis", "tennis"],
  ["natación", "swimming"],
  ["ciclismo", "cycling"],
  ["música", "music"],
  ["película", "movie"],
  ["canción", "song"],
  ["arte", "art"],
],
  adjectives: [
  ["bueno", "good", { notes: "Also: buena" }],
  ["malo", "bad", { notes: "Also: mala" }],
  ["grande", "big / large"],
  ["pequeño", "small", { notes: "Also: pequeña" }],
  ["alto", "tall / high", { notes: "Also: alta" }],
  ["bajo", "short / low", { notes: "Also: baja" }],
  ["largo", "long", { notes: "Also: larga" }],
  ["corto", "short", { notes: "Also: corta" }],
  ["ancho", "wide", { notes: "Also: ancha" }],
  ["estrecho", "narrow", { notes: "Also: estrecha" }],
  ["grueso", "thick", { notes: "Also: gruesa" }],
  ["delgado", "thin", { notes: "Also: delgada" }],
  ["nuevo", "new", { notes: "Also: nueva" }],
  ["viejo", "old", { notes: "Also: vieja" }],
  ["fácil", "easy"],
  ["difícil", "difficult"],
  ["importante", "important"],
  ["diferente", "different"],
  ["igual", "same / equal"],
  ["mejor", "better / best"],
  ["peor", "worse / worst"],
  ["primero", "first", { notes: "Also: primera" }],
  ["último", "last", { notes: "Also: última" }],
  ["mismo", "same", { notes: "Also: misma" }],
  ["otro", "other / another", { notes: "Also: otra" }],
  ["único", "only / unique", { notes: "Also: única" }],
  ["especial", "special"],
  ["normal", "normal"],
  ["común", "common"],
  ["raro", "strange / rare", { notes: "Also: rara" }],
  ["posible", "possible"],
  ["imposible", "impossible"],
  ["necesario", "necessary", { notes: "Also: necesaria" }],
  ["correcto", "correct", { notes: "Also: correcta" }],
  ["incorrecto", "incorrect", { notes: "Also: incorrecta" }],
  ["verdadero", "true", { notes: "Also: verdadera" }],
  ["falso", "false", { notes: "Also: falsa" }],
  ["perfecto", "perfect", { notes: "Also: perfecta" }],
  ["terrible", "terrible"],
  ["excelente", "excellent"],
  ["increíble", "incredible"],
  ["fantástico", "fantastic", { notes: "Also: fantástica" }],
  ["genial", "great / awesome"],
  ["útil", "useful"],
  ["inútil", "useless"],
  ["amable", "kind"],
  ["simpático", "nice / friendly", { notes: "Also: simpática" }],
  ["antipático", "unfriendly", { notes: "Also: antipática" }],
  ["agradable", "pleasant"],
  ["divertido", "fun / funny", { notes: "Also: divertida" }],
  ["aburrido", "boring / bored", { notes: "Also: aburrida" }],
  ["serio", "serious", { notes: "Also: seria" }],
  ["tranquilo", "calm", { notes: "Also: tranquila" }],
  ["nervioso", "nervous", { notes: "Also: nerviosa" }],
  ["tímido", "shy", { notes: "Also: tímida" }],
  ["extrovertido", "extroverted", { notes: "Also: extrovertida" }],
  ["generoso", "generous", { notes: "Also: generosa" }],
  ["egoísta", "selfish"],
  ["honesto", "honest", { notes: "Also: honesta" }],
  ["deshonesto", "dishonest", { notes: "Also: deshonesta" }],
  ["inteligente", "intelligent"],
  ["tonto", "stupid / silly", { notes: "Also: tonta" }],
  ["listo", "smart / ready", { notes: "Also: lista" }],
  ["trabajador", "hardworking", { notes: "Also: trabajadora" }],
  ["perezoso", "lazy", { notes: "Also: perezosa" }],
  ["responsable", "responsible"],
  ["irresponsable", "irresponsible"],
  ["cuidadoso", "careful", { notes: "Also: cuidadosa" }],
  ["descuidado", "careless", { notes: "Also: descuidada" }],
  ["impaciente", "impatient"],
  ["valiente", "brave"],
  ["cobarde", "cowardly"],
  ["curioso", "curious", { notes: "Also: curiosa" }],
  ["creativo", "creative", { notes: "Also: creativa" }],
  ["orgulloso", "proud", { notes: "Also: orgullosa" }],
  ["humilde", "humble"],
  ["cruel", "cruel"],
  ["bonito", "pretty / nice-looking", { notes: "Also: bonita" }],
  ["hermoso", "beautiful", { notes: "Also: hermosa" }],
  ["guapo", "handsome / attractive", { notes: "Also: guapa" }],
  ["feo", "ugly", { notes: "Also: fea" }],
  ["atractivo", "attractive", { notes: "Also: atractiva" }],
  ["elegante", "elegant"],
  ["famoso", "famous", { notes: "Also: famosa" }],
  ["rubio", "blonde", { notes: "Also: rubia" }],
  ["moreno", "dark-haired / brunette", { notes: "Also: morena" }],
  ["pelirrojo", "red-haired", { notes: "Also: pelirroja" }],
  ["calvo", "bald", { notes: "Also: calva" }],
  ["barbudo", "bearded", { notes: "Also: barbuda" }],
  ["feliz", "happy"],
  ["triste", "sad"],
  ["enojado", "angry", { notes: "Also: enojada" }],
  ["enfadado", "angry", { notes: "Also: enfadada" }],
  ["contento", "happy / pleased", { notes: "Also: contenta" }],
  ["emocionado", "excited", { notes: "Also: emocionada" }],
  ["preocupado", "worried", { notes: "Also: preocupada" }],
  ["asustado", "scared", { notes: "Also: asustada" }],
  ["sorprendido", "surprised", { notes: "Also: sorprendida" }],
  ["cansado", "tired", { notes: "Also: cansada" }],
  ["confundido", "confused", { notes: "Also: confundida" }],
  ["interesado", "interested", { notes: "Also: interesada" }],
  ["enamorado", "in love", { notes: "Also: enamorada" }],
  ["avergonzado", "embarrassed", { notes: "Also: avergonzada" }],
  ["relajado", "relaxed", { notes: "Also: relajada" }],
  ["estresado", "stressed", { notes: "Also: estresada" }],
  ["caliente", "hot"],
  ["fresco", "cool / fresh", { notes: "Also: fresca" }],
  ["tibio", "warm / lukewarm", { notes: "Also: tibia" }],
  ["helado", "freezing / frozen", { notes: "Also: helada" }],
  ["templado", "mild", { notes: "Also: templada" }],
  ["soleado", "sunny", { notes: "Also: soleada" }],
  ["nublado", "cloudy", { notes: "Also: nublada" }],
  ["lluvioso", "rainy", { notes: "Also: lluviosa" }],
  ["ventoso", "windy", { notes: "Also: ventosa" }],
  ["húmedo", "humid / damp", { notes: "Also: húmeda" }],
  ["seco", "dry", { notes: "Also: seca" }],
  ["nevado", "snowy", { notes: "Also: nevada" }],
  ["tropical", "tropical"],
  ["salvaje", "wild"],
  ["natural", "natural"],
  ["dulce", "sweet"],
  ["salado", "salty", { notes: "Also: salada" }],
  ["amargo", "bitter", { notes: "Also: amarga" }],
  ["ácido", "sour / acidic", { notes: "Also: ácida" }],
  ["picante", "spicy"],
  ["rico", "delicious / rich", { notes: "Also: rica" }],
  ["delicioso", "delicious", { notes: "Also: deliciosa" }],
  ["sabroso", "tasty", { notes: "Also: sabrosa" }],
  ["crudo", "raw", { notes: "Also: cruda" }],
  ["cocido", "cooked", { notes: "Also: cocida" }],
  ["maduro", "ripe / mature", { notes: "Also: madura" }],
  ["suave", "soft / smooth"],
  ["duro", "hard", { notes: "Also: dura" }],
  ["blando", "soft", { notes: "Also: blanda" }],
  ["áspero", "rough", { notes: "Also: áspera" }],
  ["liso", "smooth", { notes: "Also: lisa" }],
  ["pegajoso", "sticky", { notes: "Also: pegajosa" }],
  ["crujiente", "crispy / crunchy"],
  ["mojado", "wet", { notes: "Also: mojada" }],
  ["rojo", "red", { notes: "Also: roja" }],
  ["azul", "blue"],
  ["verde", "green"],
  ["amarillo", "yellow", { notes: "Also: amarilla" }],
  ["rosa", "pink"],
  ["morado", "purple", { notes: "Also: morada" }],
  ["violeta", "violet"],
  ["negro", "black", { notes: "Also: negra" }],
  ["blanco", "white", { notes: "Also: blanca" }],
  ["gris", "gray"],
  ["marrón", "brown"],
  ["dorado", "golden", { notes: "Also: dorada" }],
  ["plateado", "silver", { notes: "Also: plateada" }],
  ["claro", "light / pale", { notes: "Also: clara" }],
  ["oscuro", "dark", { notes: "Also: oscura" }],
  ["rápido", "fast", { notes: "Also: rápida" }],
  ["lento", "slow", { notes: "Also: lenta" }],
  ["fuerte", "strong"],
  ["débil", "weak"],
  ["pesado", "heavy", { notes: "Also: pesada" }],
  ["ligero", "light", { notes: "Also: ligera" }],
  ["profundo", "deep", { notes: "Also: profunda" }],
  ["superficial", "shallow / superficial"],
  ["lleno", "full", { notes: "Also: llena" }],
  ["vacío", "empty", { notes: "Also: vacía" }],
  ["abierto", "open", { notes: "Also: abierta" }],
  ["cerrado", "closed", { notes: "Also: cerrada" }],
  ["limpio", "clean", { notes: "Also: limpia" }],
  ["sucio", "dirty", { notes: "Also: sucia" }],
  ["seguro", "safe / secure", { notes: "Also: segura" }],
  ["peligroso", "dangerous", { notes: "Also: peligrosa" }],
  ["caro", "expensive", { notes: "Also: cara" }],
  ["barato", "cheap", { notes: "Also: barata" }],
  ["gratis", "free"],
  ["ocupado", "busy", { notes: "Also: ocupada" }],
  ["libre", "free / available"],
  ["público", "public", { notes: "Also: pública" }],
  ["privado", "private", { notes: "Also: privada" }],
  ["moderno", "modern", { notes: "Also: moderna" }],
  ["antiguo", "old / ancient", { notes: "Also: antigua" }],
  ["actual", "current"],
  ["reciente", "recent"],
  ["portátil", "portable"],
  ["digital", "digital"],
  ["electrónico", "electronic", { notes: "Also: electrónica" }],
  ["eléctrico", "electric", { notes: "Also: eléctrica" }],
  ["automático", "automatic", { notes: "Also: automática" }],
  ["manual", "manual"],
  ["inalámbrico", "wireless", { notes: "Also: inalámbrica" }],
  ["conectado", "connected", { notes: "Also: conectada" }],
  ["desconectado", "disconnected", { notes: "Also: desconectada" }],
  ["potente", "powerful"],
  ["compatible", "compatible"],
],
  opposites: [
  ["ruidoso", "noisy", { notes: "opposite of tranquilo" }],
  ["pobre", "poor", { notes: "opposite of rico" }],
  ["artificial", "artificial", { notes: "opposite of natural" }],
],
  adverbs: [
  ["siempre", "always"],
  ["nunca", "never"],
  ["jamás", "never / ever"],
  ["a veces", "sometimes"],
  ["frecuentemente", "frequently"],
  ["normalmente", "normally"],
  ["generalmente", "generally"],
  ["raramente", "rarely"],
  ["ocasionalmente", "occasionally"],
  ["diariamente", "daily"],
  ["semanalmente", "weekly"],
  ["mensualmente", "monthly"],
  ["anualmente", "annually"],
  ["ahora", "now"],
  ["hoy", "today"],
  ["ayer", "yesterday"],
  ["mañana", "tomorrow"],
  ["anoche", "last night"],
  ["antes", "before"],
  ["después", "afterward / after"],
  ["luego", "later / then"],
  ["pronto", "soon"],
  ["tarde", "late"],
  ["temprano", "early"],
  ["todavía", "still / yet"],
  ["aún", "still / yet"],
  ["ya", "already / now"],
  ["entonces", "then"],
  ["mientras", "meanwhile / while"],
  ["recientemente", "recently"],
  ["actualmente", "currently"],
  ["finalmente", "finally"],
  ["aquí", "here"],
  ["ahí", "there"],
  ["allí", "there"],
  ["allá", "over there"],
  ["cerca", "nearby"],
  ["lejos", "far away"],
  ["dentro", "inside"],
  ["fuera", "outside"],
  ["arriba", "above / upstairs"],
  ["abajo", "below / downstairs"],
  ["delante", "in front"],
  ["detrás", "behind"],
  ["encima", "on top / above"],
  ["debajo", "underneath / below"],
  ["alrededor", "around"],
  ["enfrente", "opposite / in front"],
  ["juntos", "together"],
  ["separadamente", "separately"],
  ["bien", "well"],
  ["mal", "badly"],
  ["rápidamente", "quickly"],
  ["lentamente", "slowly"],
  ["fácilmente", "easily"],
  ["difícilmente", "with difficulty"],
  ["cuidadosamente", "carefully"],
  ["especialmente", "especially"],
  ["simplemente", "simply"],
  ["exactamente", "exactly"],
  ["realmente", "really"],
  ["claramente", "clearly"],
  ["muy", "very"],
  ["más", "more"],
  ["menos", "less"],
  ["mucho", "a lot / much"],
  ["poco", "little / not much"],
  ["bastante", "quite / enough"],
  ["demasiado", "too much / too"],
  ["suficientemente", "sufficiently / enough"],
  ["casi", "almost"],
  ["apenas", "barely"],
  ["completamente", "completely"],
  ["totalmente", "totally"],
  ["absolutamente", "absolutely"],
  ["solamente", "only"],
  ["solo", "only"],
  ["incluso", "even"],
  ["quizás", "perhaps / maybe"],
  ["quizá", "perhaps / maybe"],
  ["tal vez", "maybe"],
  ["probablemente", "probably"],
  ["posiblemente", "possibly"],
  ["seguramente", "surely / probably"],
  ["definitivamente", "definitely"],
  ["ciertamente", "certainly"],
  ["obviamente", "obviously"],
  ["sin duda", "without a doubt"],
],
  pronouns: [
  ["yo", "I"],
  ["tú", "you"],
  ["él", "he"],
  ["ella", "she"],
  ["usted", "you (formal)"],
  ["nosotros", "we"],
  ["nosotras", "we"],
  ["vosotros", "you all"],
  ["vosotras", "you all"],
  ["ellos", "they"],
  ["ellas", "they"],
  ["ustedes", "you all"],
  ["me", "me"],
  ["te", "you"],
  ["lo", "him / it"],
  ["la", "her / it"],
  ["nos", "us"],
  ["os", "you all"],
  ["los", "them"],
  ["las", "them"],
  ["le", "to him / to her / to you"],
  ["les", "to them / to you all"],
  ["se", "himself / herself / yourself / themselves"],
  ["mío", "mine", { notes: "Also: mía" }],
  ["tuyo", "yours", { notes: "Also: tuya" }],
  ["suyo", "his / hers / yours / theirs", { notes: "Also: suya" }],
  ["nuestro", "ours", { notes: "Also: nuestra" }],
  ["vuestro", "yours", { notes: "Also: vuestra" }],
  ["míos", "mine", { notes: "Also: mías" }],
  ["tuyos", "yours", { notes: "Also: tuyas" }],
  ["suyos", "his / hers / yours / theirs", { notes: "Also: suyas" }],
  ["nuestros", "ours", { notes: "Also: nuestras" }],
  ["vuestros", "yours", { notes: "Also: vuestras" }],
  ["este", "this one", { notes: "Also: esta" }],
  ["estos", "these", { notes: "Also: estas" }],
  ["ese", "that one", { notes: "Also: esa" }],
  ["esos", "those", { notes: "Also: esas" }],
  ["aquel", "that one over there", { notes: "Also: aquella" }],
  ["aquellos", "those over there", { notes: "Also: aquellas" }],
  ["alguien", "someone"],
  ["algo", "something"],
  ["nadie", "nobody"],
  ["nada", "nothing"],
  ["alguno", "some / one", { notes: "Also: alguna" }],
  ["ninguno", "none / no one", { notes: "Also: ninguna" }],
  ["cualquiera", "anyone / anyone at all"],
  ["cada uno", "each one"],
  ["todos", "everyone / all"],
  ["todo", "everything / all"],
  ["ambos", "both"],
  ["que", "that / which / who"],
  ["quien", "who / whom", { notes: "Also: quienes" }],
  ["cual", "which", { notes: "Also: cuales" }],
  ["cuyo", "whose", { notes: "Also: cuya" }],
  ["donde", "where"],
  ["cuando", "when"],
  ["como", "how / as"],
],
  determiners: [
  ["el", "the"],
  ["un", "a / an"],
  ["una", "a / an"],
  ["unos", "some"],
  ["unas", "some"],
  ["mi", "my"],
  ["mis", "my"],
  ["tu", "your"],
  ["tus", "your"],
  ["su", "his / her / your / their"],
  ["sus", "his / her / your / their"],
  ["cada", "each / every"],
  ["otros", "others", { notes: "Also: otras" }],
  ["algún", "some / any", { notes: "Also: alguno, alguna" }],
  ["algunos", "some", { notes: "Also: algunas" }],
  ["ningún", "no / none", { notes: "Also: ninguno, ninguna" }],
  ["muchos", "many", { notes: "Also: muchas" }],
  ["pocos", "few", { notes: "Also: pocas" }],
  ["varios", "several", { notes: "Also: varias" }],
  ["suficiente", "enough", { notes: "Also: suficientes" }],
],
  connectors: [
  ["y", "and"],
  ["o", "or"],
  ["pero", "but"],
  ["porque", "because"],
  ["pues", "well / because"],
  ["también", "also"],
  ["tampoco", "neither / either"],
  ["además", "besides / furthermore"],
  ["aunque", "although / even though"],
  ["si", "if"],
  ["ni", "neither / nor"],
  ["sino", "but rather"],
  ["sino que", "but rather"],
  ["así", "so / this way"],
  ["así que", "so / therefore"],
  ["por eso", "that's why / therefore"],
  ["por lo tanto", "therefore"],
  ["sin embargo", "however"],
  ["en cambio", "on the other hand / instead"],
  ["de hecho", "in fact"],
  ["por ejemplo", "for example"],
  ["en realidad", "actually"],
  ["no obstante", "nevertheless"],
  ["mientras que", "whereas / while"],
  ["por otro lado", "on the other hand"],
  ["a pesar de", "despite"],
  ["a pesar de que", "despite the fact that"],
  ["ya que", "since / because"],
  ["puesto que", "since / given that"],
  ["debido a", "due to"],
  ["debido a que", "due to the fact that"],
  ["gracias a", "thanks to"],
  ["por", "because of / for"],
  ["a causa de", "because of"],
  ["por consiguiente", "consequently"],
  ["en consecuencia", "consequently"],
  ["de modo que", "so / in such a way that"],
  ["de manera que", "so / in such a way that"],
  ["por esta razón", "for this reason"],
  ["primero de todo", "first of all"],
  ["en primer lugar", "firstly"],
  ["mientras tanto", "meanwhile"],
  ["al mismo tiempo", "at the same time"],
  ["a continuación", "next"],
  ["por último", "lastly"],
  ["al final", "in the end"],
  ["desde entonces", "since then"],
  ["es decir", "that is / in other words"],
  ["o sea", "in other words / I mean"],
  ["en otras palabras", "in other words"],
  ["sobre todo", "above all / especially"],
  ["por supuesto", "of course"],
  ["a menos que", "unless"],
  ["siempre que", "as long as"],
  ["con tal de que", "provided that"],
  ["en caso de que", "in case"],
  ["a condición de que", "on condition that"],
  ["solo si", "only if"],
  ["para", "for / in order to"],
  ["para que", "so that"],
  ["con el fin de", "in order to"],
  ["con el objetivo de", "with the goal of"],
  ["a fin de", "in order to"],
],
  prepositions: [
  ["a", "to / at"],
  ["ante", "before / in the presence of"],
  ["con", "with"],
  ["contra", "against"],
  ["de", "of / from"],
  ["desde", "from / since"],
  ["durante", "during"],
  ["en", "in / on / at"],
  ["entre", "between / among"],
  ["hacia", "toward"],
  ["hasta", "until / up to"],
  ["según", "according to"],
  ["sin", "without"],
  ["sobre", "on / about / over"],
  ["tras", "after / behind"],
  ["al lado", "next to"],
  ["junto a", "next to"],
  ["alrededor de", "around"],
  ["enfrente de", "opposite / in front of"],
  ["a la derecha", "to the right"],
  ["a la izquierda", "to the left"],
],
  time: [
  ["lunes", "Monday"],
  ["martes", "Tuesday"],
  ["miércoles", "Wednesday"],
  ["jueves", "Thursday"],
  ["viernes", "Friday"],
  ["sábado", "Saturday"],
  ["domingo", "Sunday"],
  ["enero", "January"],
  ["febrero", "February"],
  ["marzo", "March"],
  ["abril", "April"],
  ["mayo", "May"],
  ["junio", "June"],
  ["julio", "July"],
  ["agosto", "August"],
  ["septiembre", "September"],
  ["octubre", "October"],
  ["noviembre", "November"],
  ["diciembre", "December"],
  ["primavera", "spring"],
  ["verano", "summer"],
  ["otoño", "fall / autumn"],
  ["invierno", "winter"],
  ["hora", "hour / time"],
  ["minuto", "minute"],
  ["día", "day"],
  ["semana", "week"],
  ["mes", "month"],
  ["año", "year"],
  ["década", "decade"],
  ["siglo", "century"],
  ["noche", "night"],
  ["medianoche", "midnight"],
  ["mediodía", "noon"],
  ["fecha", "date"],
  ["calendario", "calendar"],
],
  expressions: [
  ["¿cómo estás?", "how are you?"],
  ["¿qué tal?", "how's it going?"],
  ["¿qué pasa?", "what's happening? / what's wrong?"],
  ["¿qué haces?", "what are you doing?"],
  ["¿qué quieres?", "what do you want?"],
  ["¿qué significa?", "what does it mean?"],
  ["¿cómo se dice...?", "how do you say...?"],
  ["¿cómo se llama...?", "what is ... called?"],
  ["¿dónde está...?", "where is...?"],
  ["¿cuánto cuesta?", "how much does it cost?"],
  ["¿qué hora es?", "what time is it?"],
  ["¿por qué?", "why?"],
  ["¿por qué no?", "why not?"],
  ["¿para qué?", "what for?"],
  ["¿puedes ayudarme?", "can you help me?"],
  ["¿me puedes ayudar?", "can you help me?"],
  ["¿puede repetir?", "can you repeat?"],
  ["no entiendo", "I don't understand"],
  ["no sé", "I don't know"],
  ["no importa", "it doesn't matter"],
  ["no pasa nada", "it's okay / no problem"],
  ["ya entiendo", "I understand now"],
  ["ya veo", "I see"],
  ["tengo una pregunta", "I have a question"],
  ["tengo que irme", "I have to go"],
  ["tengo que hacerlo", "I have to do it"],
  ["quiero saber", "I want to know"],
  ["quiero decir", "I mean / I want to say"],
  ["no quiero", "I don't want to"],
  ["me gusta", "I like it"],
  ["no me gusta", "I don't like it"],
  ["me parece", "it seems to me"],
  ["creo que", "I think that"],
  ["pienso que", "I think that"],
  ["sé que", "I know that"],
  ["no creo que", "I don't think that"],
  ["depende", "it depends"],
  ["puede ser", "it could be / maybe"],
  ["claro que sí", "of course / definitely"],
  ["claro que no", "of course not"],
  ["de acuerdo", "okay / agreed"],
  ["está bien", "it's okay / alright"],
  ["vale", "okay / alright"],
  ["gracias", "thank you"],
  ["de nada", "you're welcome"],
  ["por favor", "please"],
  ["perdón", "sorry / excuse me"],
  ["disculpe", "excuse me / sorry"],
  ["con permiso", "excuse me / may I pass?"],
  ["hasta luego", "see you later"],
  ["hasta mañana", "see you tomorrow"],
  ["nos vemos", "see you"],
  ["buenos días", "good morning"],
  ["buenas tardes", "good afternoon"],
  ["buenas noches", "good evening / good night"],
  ["sí", "yes"],
  ["no", "no"],
  ["cómo", "how"],
  ["qué", "what"],
  ["quién", "who"],
  ["dónde", "where"],
  ["cuándo", "when"],
  ["cuánto", "how much / how many"],
  ["por qué", "why"],
  ["para qué", "what for / why"],
],
  questionWords: [
  ["quiénes", "who (plural)"],
  ["cuál", "which / what"],
  ["cuáles", "which / what (plural)"],
  ["adónde", "where to"],
  ["de dónde", "from where"],
  ["cuánta", "how much"],
  ["cuántos", "how many"],
  ["cuántas", "how many"],
  ["qué tipo de", "what kind of"],
],
  negation: [
  ["ni siquiera", "not even"],
  ["nunca más", "never again"],
  ["ya no", "no longer"],
],
  comparison: [
  ["tan", "as / so"],
  ["tanto", "so much / as much"],
  ["igual que", "just like / the same as"],
  ["más que", "more than"],
  ["menos que", "less than"],
  ["mejor que", "better than"],
  ["peor que", "worse than"],
  ["tanto como", "as much as"],
  ["más o menos", "more or less"],
  ["en comparación con", "compared with"],
],
  phrasePatterns: [
  ["quiero", "I want"],
  ["quieres", "you want"],
  ["necesito", "I need"],
  ["necesitas", "you need"],
  ["puedo", "I can"],
  ["puedes", "you can"],
  ["puede", "he/she/you can"],
  ["tengo", "I have"],
  ["tienes", "you have"],
  ["hay", "there is / there are"],
  ["está", "he/she/it is"],
  ["están", "they are"],
  ["voy", "I go / I'm going"],
  ["vas", "you go / you're going"],
  ["vamos", "we go / we're going"],
  ["sé", "I know"],
  ["sabes", "you know"],
  ["creo", "I think / I believe"],
  ["crees", "you think / you believe"],
  ["pienso", "I think"],
  ["piensas", "you think"],
  ["me gustaría", "I would like"],
  ["me gustaría saber", "I would like to know"],
  ["¿puedo...?", "can I...?"],
  ["¿puedes...?", "can you...?"],
  ["¿podrías...?", "could you...?"],
  ["¿tienes...?", "do you have...?"],
  ["¿hay...?", "is there...? / are there...?"],
  ["¿dónde puedo...?", "where can I...?"],
  ["¿cómo puedo...?", "how can I...?"],
  ["¿qué debo...?", "what should I...?"],
  ["¿qué tengo que...?", "what do I have to...?"],
  ["no puedo", "I can't"],
  ["no tengo", "I don't have"],
  ["no hay", "there isn't / there aren't"],
],
  verbPrepositionCombinations: [
  ["soñar con", "to dream about"],
  ["consistir en", "to consist of"],
  ["luchar por", "to fight for"],
  ["esperar a", "to wait for"],
  ["invitar a", "to invite"],
  ["dedicarse a", "to dedicate oneself to"],
  ["alegrarse de", "to be happy about"],
  ["quejarse de", "to complain about"],
],
};
